/* Énigmes originales : les règles fictives sont précisées dans chaque énoncé. */
window.CosmicMissions = {
  logic: { name: "Station des paradoxes", emoji: "🔐", color: "#c4a2ff", description: "Déductions, indices et ordres de passage", rows: [
    ["Tous les drones bleus ont un badge. Nova est un drone bleu. Que sait-on ?", ["Nova a un badge", "Nova est rouge", "Nova n'a pas de badge", "Tous les badges sont bleus"], 0, "Applique la règle à Nova.", "Nova appartient au groupe des drones bleus ; la règle lui impose donc un badge."],
    ["Une seule soute contient une batterie. A et B sont vides. Elle est dans…", ["A", "B", "C", "A et C"], 2, "Élimine les soutes impossibles.", "Sur les trois soutes A, B et C, seule C reste possible."],
    ["Lina arrive avant Milo, et Milo avant Noor. Qui arrive en dernier ?", ["Lina", "Milo", "Noor", "Impossible à savoir"], 2, "Écris la chaîne des arrivées.", "L'ordre est Lina, Milo, Noor."],
    ["Si l'alarme sonne, la porte se ferme. La porte est ouverte. Que peut-on conclure ?", ["L'alarme sonne", "L'alarme ne sonne pas", "La porte est cassée", "Le courant est coupé"], 1, "Une alarme imposerait une porte fermée.", "Une porte ouverte exclut l'alarme selon la règle donnée. Rien n'indique une panne."],
    ["Exactement un voyant est allumé parmi rouge et bleu. Le rouge est éteint. Le bleu est…", ["Éteint", "Allumé", "Clignotant", "Cassé"], 1, "Il doit rester un voyant allumé.", "Puisque le rouge est éteint et qu'il en faut exactement un, c'est le bleu."],
    ["A dit : « Le cristal est dans B. » B dit : « Il n'est pas dans B. » Combien de ces deux phrases sont vraies ?", ["Zéro", "Une", "Deux", "Trois"], 1, "Les phrases sont des contraires exacts.", "Le cristal est dans B ou n'y est pas : exactement une des phrases est vraie."],
    ["Trois robots portent des numéros différents : 1, 2, 3. Rho n'est ni 1 ni 3. Son numéro ?", ["1", "2", "3", "0"], 1, "Il ne reste qu'une possibilité.", "En retirant 1 et 3, Rho porte nécessairement le numéro 2."],
    ["Chaque pilote est formé au secours. Certains pilotes sont musiciens. Quelle phrase est certaine ?", ["Tous les musiciens sont pilotes", "Aucun musicien n'est formé", "Certains musiciens sont formés au secours", "Tous les secouristes sont musiciens"], 2, "Regarde les pilotes qui sont aussi musiciens.", "Ces pilotes musiciens sont formés comme tous les pilotes. On ne sait rien des autres musiciens."],
    ["Une capsule est plus lourde qu'un cube. Le cube est plus lourd qu'une sphère. Le plus léger est…", ["La capsule", "Le cube", "La sphère", "Ils pèsent pareil"], 2, "Compare les trois masses dans l'ordre.", "Capsule > cube > sphère : la sphère est la plus légère."],
    ["La règle impose un badge pour entrer. Ivo est entré en respectant la règle. Que possédait-il ?", ["Un casque", "Un badge", "Une clé rouge", "Une combinaison"], 1, "Cherche la condition obligatoire.", "Le badge est nécessaire pour entrer. Les autres objets ne sont pas mentionnés."],
    ["Une porte s'ouvre seulement si A ET B sont actifs. A est actif, B est inactif. Peut-elle s'ouvrir ?", ["Oui", "Non", "Seulement la nuit", "Une fois sur deux"], 1, "ET exige les deux conditions.", "L'absence de B empêche l'ouverture, même si A est actif."],
    ["Un circuit s'allume si A OU B est actif, y compris les deux. A et B sont actifs. Le circuit est…", ["Allumé", "Éteint", "Bloqué", "Indéterminé"], 0, "Ce OU accepte aussi les deux entrées.", "Au moins une entrée est active ; le circuit s'allume."],
  ] },
  navigation: { name: "Journal de bord", emoji: "🧭", color: "#78e9c0", description: "Trajets, ressources et décisions de mission", rows: [
    ["Tu fais face au nord. Tu tournes à droite, puis à gauche. Tu regardes…", ["Le nord", "Le sud", "L'est", "L'ouest"], 0, "Les deux rotations s'annulent.", "Nord → est → nord."],
    ["Sur une carte, 1 case vaut 5 km. Deux balises sont séparées de 6 cases. Distance ?", ["11 km", "25 km", "30 km", "60 km"], 2, "Multiplie les cases par leur échelle.", "6 × 5 = 30 km."],
    ["Le rover avance de 3 cases à l'est puis de 3 à l'ouest. Où termine-t-il ?", ["3 cases au nord", "Au départ", "6 cases à l'est", "3 cases au sud"], 1, "Les déplacements sont opposés.", "Les trois cases vers l'ouest annulent celles vers l'est."],
    ["Il reste 24 litres de réserve. Chaque trajet consomme 6 litres. Combien de trajets complets ?", ["3", "4", "6", "8"], 1, "Divise la réserve par la consommation.", "24 ÷ 6 = 4 trajets complets."],
    ["Un signal part à 14 h 50 et met 25 minutes. À quelle heure arrive-t-il ?", ["14 h 75", "15 h 05", "15 h 15", "15 h 25"], 2, "Passe d'abord l'heure suivante.", "10 minutes mènent à 15 h, puis 15 autres à 15 h 15."],
    ["Sur une grille, on part de (2, 3). Aller à l'est augmente x. Après 4 cases à l'est :", ["(2, 7)", "(6, 3)", "(4, 3)", "(2, −1)"], 1, "Seule la première coordonnée change.", "x devient 2 + 4 = 6 ; y reste 3."],
    ["La route A dure 12 min. La route B dure 8 min mais impose 7 min d'attente. La plus rapide ?", ["A", "B", "Égalité", "Impossible à savoir"], 0, "Ajoute le temps d'attente.", "B prend 15 minutes au total, contre 12 pour A."],
    ["Une batterie est à 80 %. Une tâche consomme 15 points de pourcentage. Après deux tâches ?", ["65 %", "50 %", "30 %", "95 %"], 1, "Retire deux fois 15 points.", "80 − 15 − 15 = 50 %."],
    ["Tu regardes l'ouest et fais demi-tour. Tu regardes…", ["Le nord", "Le sud", "L'est", "L'ouest"], 2, "Un demi-tour inverse la direction.", "L'est est opposé à l'ouest."],
    ["Trois équipes se partagent également 18 rations. Combien par équipe ?", ["3", "6", "9", "12"], 1, "Un partage égal est une division.", "18 ÷ 3 = 6 rations par équipe."],
    ["La navette part toutes les 12 minutes, dès 10 h 00. Premier départ après 10 h 20 ?", ["10 h 22", "10 h 24", "10 h 30", "10 h 36"], 1, "Liste les départs successifs.", "Les départs sont 10 h 00, 10 h 12, 10 h 24…"],
    ["Un trajet de 20 km est parcouru à 10 km/h constants. Quelle durée ?", ["30 min", "1 h", "2 h", "4 h"], 2, "Durée = distance ÷ vitesse.", "20 ÷ 10 = 2 heures."],
  ] },
  codes: { name: "Signaux cryptés", emoji: "📡", color: "#ffc878", description: "Messages, séquences et symboles à décoder", rows: [
    ["Code A=1, B=2, C=3… Que représente 3-1-2 ?", ["ABC", "CAB", "BAC", "CBA"], 1, "Remplace chaque nombre par sa lettre.", "3 donne C, 1 donne A et 2 donne B : CAB."],
    ["Chaque nombre double : 3, 6, 12, 24… Le suivant ?", ["30", "36", "48", "72"], 2, "Multiplie le dernier par deux.", "24 × 2 = 48."],
    ["Le motif répète ○ △ □. Après ○ △ □ ○ △ vient…", ["○", "△", "□", "◇"], 2, "Le bloc comporte trois symboles.", "Le second bloc se termine lui aussi par □."],
    ["Un code remplace chaque lettre par la suivante : A→B. Que devient LUNE ?", ["MVOF", "KTMD", "MVNE", "LVOF"], 0, "Décale les quatre lettres.", "L→M, U→V, N→O, E→F donnent MVOF."],
    ["Le message est écrit à l'envers : RATS. Quel était le mot ?", ["STAR", "TSAR", "ARTS", "TARS"], 0, "Lis de droite à gauche.", "RATS lu en sens inverse donne STAR."],
    ["Le signal suit +3 à chaque étape : 2, 5, 8, 11… Ensuite ?", ["12", "13", "14", "15"], 2, "Ajoute 3 à 11.", "11 + 3 = 14."],
    ["Sur ce panneau, ★ vaut 5 et ● vaut 2. Que vaut ★ + ● + ● ?", ["7", "9", "10", "12"], 1, "Remplace les symboles par leur valeur.", "5 + 2 + 2 = 9."],
    ["Un bit ne peut valoir que 0 ou 1. Quel message respecte cette règle ?", ["1021", "1200", "1010", "0112"], 2, "Repère les messages contenant un 2.", "Seul 1010 utilise exclusivement 0 et 1."],
    ["Pour décoder, retire 4 à chaque nombre. Que devient 9-6-8 ?", ["5-2-4", "13-10-12", "4-2-5", "5-3-4"], 0, "Applique la même opération trois fois.", "9−4=5, 6−4=2 et 8−4=4."],
    ["Une balise alterne long, court, long, court… Le cinquième signal sera…", ["Long", "Court", "Silencieux", "Double"], 0, "Les positions impaires sont identiques.", "Les signaux 1, 3 et 5 sont longs."],
    ["Le code demandé contient exactement deux lettres A. Lequel convient ?", ["ABCD", "BAAC", "AAAA", "BCDE"], 1, "Compte les A de chaque proposition.", "BAAC contient deux A ; les autres en contiennent un, quatre ou zéro."],
    ["La règle ajoute les deux termes précédents : 1, 2, 3, 5, 8… Ensuite ?", ["10", "11", "13", "16"], 2, "Additionne 5 et 8.", "5 + 8 = 13."],
  ] },
};
